from pptx import Presentation
from pptx.util import Pt, Inches
from pptx.dml.color import RGBColor
from io import BytesIO
import os


# ---------- THEME COLORS ----------
THEMES = {
    "academic": {
        "bg": RGBColor(245, 245, 255),
        "title": RGBColor(20, 20, 60),
        "text": RGBColor(30, 30, 30)
    },
    "dark": {
        "bg": RGBColor(30, 30, 60),
        "title": RGBColor(255, 255, 255),
        "text": RGBColor(220, 220, 220)
    }
}


# ---------- BACKGROUND ----------
def _set_bg(slide, color):
    fill = slide.background.fill
    fill.solid()
    fill.fore_color.rgb = color


# ---------- SPEAKER NOTES ----------
def _add_speaker_notes(slide, text):
    try:
        notes = slide.notes_slide.notes_text_frame
        notes.text = text
    except:
        pass


# ---------- LOGO ----------
def add_logo(slide):

    logo_path = "assets/logo.png"

    if os.path.exists(logo_path):
        slide.shapes.add_picture(
            logo_path,
            Inches(0.30),
            Inches(0.30),
            width=Inches(1)
        )


# ---------- FOOTER ----------
def add_footer(slide, slide_no):

    textbox = slide.shapes.add_textbox(
        Inches(0.2),
        Inches(6.9),
        Inches(9),
        Inches(0.3)
    )

    textbox.text_frame.text = (
        f"RajniAI | Developed by Rajni Tiwari, CSE, CMRIT | Slide {slide_no}"
    )

    p = textbox.text_frame.paragraphs[0]
    p.font.size = Pt(15)
    p.font.color.rgb = RGBColor(100, 100, 100)


# ---------- MAIN PPT BUILDER ----------
def build_pptx(plan, theme="academic"):

    prs = Presentation()

    style = THEMES.get(
        theme,
        THEMES["academic"]
    )

    # ==================================================
    # TITLE SLIDE
    # ==================================================
    slide = prs.slides.add_slide(
        prs.slide_layouts[0]
    )

    _set_bg(slide, style["bg"])

    add_logo(slide)
    add_footer(slide, 1)

    title = slide.shapes.title
    subtitle = slide.placeholders[1]

    title.text = plan.get(
        "title",
        "Research Presentation"
    )

    subtitle.text = plan.get(
        "subtitle",
        "Generated by RajniAI"
    )

    title.text_frame.paragraphs[0].font.size = Pt(34)
    title.text_frame.paragraphs[0].font.bold = True
    title.text_frame.paragraphs[0].font.color.rgb = style["title"]

    # ==================================================
    # CONTENT SLIDES
    # ==================================================
    slide_no = 2

    for sl in plan.get("slides", []):

        slide = prs.slides.add_slide(
            prs.slide_layouts[1]
        )

        _set_bg(slide, style["bg"])

        add_logo(slide)
        add_footer(slide, slide_no)

        slide_no += 1

        title_shape = slide.shapes.title

        title_shape.text = sl.get(
            "title",
            ""
        )

        title_shape.text_frame.paragraphs[0].font.size = Pt(24)
        title_shape.text_frame.paragraphs[0].font.bold = True
        title_shape.text_frame.paragraphs[0].font.color.rgb = style["title"]

        content = slide.placeholders[1]

        tf = content.text_frame
        tf.clear()

        speaker_notes = []

        bullets = sl.get("bullets", [])

        for i, bullet in enumerate(bullets):

            bullet = str(bullet).strip()

            if not bullet:
                continue

            # Split long sentences
            sentences = [
                s.strip()
                for s in bullet.split(".")
                if s.strip()
            ]

            if len(sentences) == 0:
                sentences = [bullet]

            for j, sentence in enumerate(sentences):

                if i == 0 and j == 0:
                    p = tf.paragraphs[0]
                else:
                    p = tf.add_paragraph()

                p.text = sentence
                p.level = 0
                p.font.size = Pt(18)
                p.font.color.rgb = style["text"]

            speaker_notes.append(bullet)

        _add_speaker_notes(
            slide,
            "\n".join(speaker_notes)
        )

    # ==================================================
    # REFERENCES SLIDE
    # ==================================================
    slide = prs.slides.add_slide(
        prs.slide_layouts[1]
    )

    _set_bg(slide, style["bg"])

    add_logo(slide)
    add_footer(slide, slide_no)

    slide.shapes.title.text = "References"

    tf = slide.placeholders[1].text_frame

    p = tf.paragraphs[0]
    p.text = "Refer to the paper reference section."

    # ==================================================
    # THANK YOU SLIDE
    # ==================================================
    slide = prs.slides.add_slide(
        prs.slide_layouts[6]
    )

    _set_bg(slide, style["bg"])

    add_logo(slide)
    add_footer(slide, slide_no + 1)

    textbox = slide.shapes.add_textbox(
        Inches(1),
        Inches(2),
        Inches(8),
        Inches(1)
    )

    textbox.text_frame.text = "Thank You"

    p = textbox.text_frame.paragraphs[0]

    p.font.size = Pt(32)
    p.font.bold = True
    p.font.color.rgb = style["title"]

    # ==================================================
    # SAVE PPT
    # ==================================================
    buffer = BytesIO()

    prs.save(buffer)

    buffer.seek(0)

    return buffer